---
image:
  repository: sigp/lighthouse
  tag: v5.3.0
storage:
  storageClassName: local
  pvcSize: 1200Gi
# nodeSelector is optional. Uncomment to use.
# nodeSelector:
#   key: value
lighthouse:
  network: mainnet
  metrics:
    enabled: false
  monitoringEndpoint:
  beacon:
    enabled: true
    resources:
      limits:
        cpu: 6
        memory: 24Gi
      requests:
        cpu: 3
        memory: 16Gi
    ingress:
      http:
        enabled: false
        annotations: {}
        hosts:
          - host: http-geth.example.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
    metricsPort: 5054
    http:
      enabled: true
      port: 5052
    p2p:
      hostPorts: false
      tcpPort: 9000
      udpPort: 9000
    # use a checkpoint sync provider to speed up syncs from scratch
    checkpointSync:
      enabled: true
      url: https://mainnet.checkpoint.sigp.io
    purgeDb: false
    # this defines the connection to the execution layer - required by a consensus client like lighthouse
    # all of these values are required if in beacon mode
    # however, if they are not provided, lighthouse pod should still deploy and run for long enough to satisfy liveness and readiness probes, so you can still check things out
    # jwt must not include a leading '0x'
    executionEndpoint:
      host:
      port:
      jwt:
    # you most likely want to set this
    # this is how eth peers will target you. this address and port must be accessible from the outside to your beacon node
    # host = your external ip
    # port = your external port
    enr:
      host:
      port:
    disableUpnp: true
    validatorMonitorAuto: true
    prunePayloads: true
    genesisBackfill: false
  validator:
    enabled: false
    resources:
      limits:
        cpu: 6
        memory: 24Gi
      requests:
        cpu: 3
        memory: 16Gi
    ingress:
      http:
        enabled: false
        annotations: {}
        hosts:
          - host: http-geth.example.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
    metricsPort: 5064
    http:
      enabled: true
      port: 5062
    # if you are running the beacon node as part of this helm release, the beacon node container will be available in the same pod
    # otherwise, change this url
    beaconNodeUrl: http://localhost:5052
    suggestedFeeRecipient:
    graffiti:
